theme = "japan"

[editor]
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["file-name", "spinner", "diagnostics"]
right = ["position"]
